fix: add handler to http error in get ticket request
eol-uchile/edx-ucursos pull request #10
Opened 2024-07-18 22:51 UTC by fsologureng

2024-07-19 19:31 UTC, catalinaIlabaca requested changes

2024-07-19 19:47 UTC, tomaspemora approved these changes

2024-07-19 19:51 UTC, fsologureng commented on edxucursos/views.py
> +            return {'result': 'error'}
Concuerdo contigo, y de hecho pensé hacerlo, pero el código está evaluando la salida tal cual está ahí y preferí no hacer cambios mayores:
https://github.com/eol-uchile/edx-ucursos/blob/474fc10bd1ba6889dd1d2e4236fd9f761af7b817/edxucursos/views.py#L51-L56

2024-07-19 19:52 UTC, fsologureng commented on edxucursos/views.py
> +            return {'result': 'error'}
Sí podría quitarle el bind a `e` porque no se usa :+1:

2024-07-19 23:10 UTC, fsologureng commented
Aunque esté listo, este pr no será mezclado hasta que el #11 esté mezclado y rebaseado acá.

2024-07-23 14:01 UTC, tomaspemora approved these changes
Veo que pasó todos los test esta vez y no puedo probarlo en mi local porque necesitaría un u-cursos. Tendríamos que probar los endpoint no más, pero no modificaste ninguno así que aprobaré

2024-07-23 14:04 UTC, fsologureng commented
> Veo que pasó todos los test esta vez y no puedo probarlo en mi local porque necesitaría un u-cursos. Tendríamos que probar los endpoint no más, pero no modificaste ninguno así que aprobaré

No sé si entendí :sweat_smile:

2024-07-23 15:04 UTC, catalinaIlabaca approved these changes

2024-07-23 15:25 UTC, merged