fix: adapts tests to latest changes from uchileedxlogin pkg
eol-uchile/edx-ucursos pull request #11
Opened 2024-07-19 17:58 UTC by fsologureng

- changes patches of a method and a response from uchileedxlogin pkg.
- fixes creation of coverage rc file.
- updates coverage badge.

2024-07-19 19:26 UTC, tomaspemora requested changes

2024-07-19 19:40 UTC, fsologureng commented on edxucursos/tests.py
> +def create_user(user_data, have_pass):
No se ocupa. Lo que pasa es que ese método se usa para [parchar](https://github.com/eol-uchile/edx-ucursos/blob/db54c2527bfd09894965cc6cbc52b0cb1468264e/edxucursos/tests.py#L266) (`@patch`) la función [create_user_by_data](https://github.com/eol-uchile/uchileedxlogin/blob/master/uchileedxlogin/views.py#L248) de uchileedxlogin que [cambió de firma](https://github.com/eol-uchile/uchileedxlogin/commit/50c1a843ef3787378ea4de71be8f084fdbfa0ee7#diff-24ced8ce3e1b9621b7ec201fde348e77e1df42ad40ced3946bb08f6047c96e59) y nunca se actualizó acá en su parche para los tests que la usan, resultando en un error de llamada (runtime).

2024-07-19 19:49 UTC, tomaspemora approved these changes

2024-07-22 22:19 UTC, catalinaIlabaca approved these changes

2024-07-23 13:07 UTC, merged